# Generated by Django 5.2.5 on 2025-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='compose_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='frontend_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='project_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
