# Generated by Django 5.1.4 on 2025-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionrequest',
            name='db_app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='db_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
