# Generated by Django 5.2.5 on 2025-09-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0002_provisionrequest_db_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionrequest',
            name='failed_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='progress',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROJECT_CREATED', 'Project created'), ('BACKEND_CREATED', 'Backend created'), ('BACKEND_GIT_ATTACHED', 'Backend git attached'), ('BACKEND_BUILD_CONFIGURED', 'Backend build configured'), ('DB_CREATED', 'DB created'), ('BACKEND_ENV_CONFIGURED', 'Backend env configured'), ('POSTGRES_DEPLOY_TRIGGERED', 'Postgres deploy triggered'), ('APPLICATION_DEPLOY_TRIGGERED', 'Application deploy triggered'), ('FRONTEND_CREATED', 'Frontend created'), ('FRONTEND_GIT_ATTACHED', 'Frontend git attached'), ('FRONTEND_BUILD_CONFIGURED', 'Frontend build configured'), ('FRONTEND_DEPLOY_TRIGGERED', 'Frontend deploy triggered'), ('DOMAINS_CONFIGURED', 'Domains configured'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
