# Generated by Django 5.2.5 on 2025-09-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0003_provisionrequest_failed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisionrequest',
            name='failed_at',
        ),
        migrations.RemoveField(
            model_name='provisionrequest',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='provisionrequest',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='provisionrequest',
            name='running',
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_build_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_deploy_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_env_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_git_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='db_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='domains_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='frontend_build_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='frontend_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='frontend_deploy_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='frontend_git_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='postgres_deploy_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='project_created',
            field=models.BooleanField(default=False),
        ),
    ]
