# Generated by Django 5.2.5 on 2025-09-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioner', '0004_remove_provisionrequest_failed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_health_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='backend_next_wait',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='provisionrequest',
            name='super_user_created',
            field=models.BooleanField(default=False),
        ),
    ]
